### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by minidubsy** [HSLix/LixAssistantLimbusCompany#26]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

Failed to execute script 'main' due to unhandled exception: 'charmap' codec can't encode characters in position 0-9 character maps to <undefined> 

Traceback (most recent call last):
  File "main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "scriptGUI.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "myGUI.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "src\common\listenAndExit.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "src\log\nbLog.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "nb_log\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "nb_log\set_nb_log_config.py", line 16, in <module>
  File "nb_log\simple_print.py", line 52, in sprint
  File "nb_log\simple_print.py", line 33, in _sprint
  File "nb_log\simple_print.py", line 23, in stderr_write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-9: character maps to <undefined>

### 重现问题

Open LALC

### 日志文件

Traceback (most recent call last):
  File "main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "scriptGUI.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "myGUI.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "src\common\listenAndExit.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "src\log\nbLog.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "nb_log\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 386, in exec_module
  File "nb_log\set_nb_log_config.py", line 16, in <module>
  File "nb_log\simple_print.py", line 52, in sprint
  File "nb_log\simple_print.py", line 33, in _sprint
  File "nb_log\simple_print.py", line 23, in stderr_write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-9: character maps to <undefined>

### 截图

![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/149075764/f6fbcde4-592b-4a90-9f3d-5fee09150611)

when i press lalc shortcut to open the exe

### 应该是？

lalc opens up..

### 其他信息

Windows 10
Language : English & Mandarin
1920x1080 res

**Comment by HSLix** [comment]
It's 99.9 percent the encoding problem. You can have a try on the following steps.

Here are the steps to follow in Windows operating system:

1、Open Control Panel.
2、Select "Clock and Region".
3、In the "Region" section, click on "Change date, time, or number formats".
4、In the pop-up window, select the "Administrative" tab.
5、In the "Language for non-Unicode programs" section, click on "Change system locale".
6、Select "Use Unicode UTF-8 for worldwide language support".
7、Click the "OK" button and follow the system prompts to restart your computer.
